### PR TITLE
Pass currentPrecedence when formatting the RHS of a binary operator

### LINKED ISSUE #16: Optimizing away braces in boolean expression can lead to wrong results
I've got another one: when overriding the `and`/`or` operator precedence via braces, the minified code will be invalid, because the braces are removed.

Example: `print(false and (false or true))` evaluates to `false` but it becomes `print(false and false or true)` which evaluates to `true`.

### PR DESCRIPTION
**Pull request by aecay**
Fixes #16

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Thanks. Could you please add some tests for the behavior your changing?

**Comment by aecay** [comment]
Thanks for the reminder about tests.  I have added them, and fixed another bug.  The resultant code is a bit complicated -- I've tried to comment it well.

The issue is that `1-(2-3)` can't be minified to `1-2-3`, but `1+(2+3)` can have its parens dropped.  This requires a somewhat detailed descriptions of the differences between + and - (which have identical precedence and syntactic features, but differ in their semantics).  The same goes for `*` and `/` (with the added complication introduced by `%`).

**Comment by mathiasbynens** [comment]
Nice work, @aecay! I’ll be able to do proper review in the morning and merge it then. Cheers!

**Comment by mathiasbynens** [comment]
Thanks! Next time, please follow the existing coding style (e.g. tabs for indentation, single quotes for strings).

**Pull request closed without merging**
