### PR TITLE
Don't remove parens around function call declarations

### PR DESCRIPTION
**Pull request by EdanPyx**
Fixes https://github.com/mathiasbynens/luamin/issues/23

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Could you add some tests?

**Comment by EdanPyx** [comment]
Ok I added a test, can't think of anything else.

**Comment by mathiasbynens** [comment]
The other test case mentioned in #15 is `print(({})[1])`.

**Comment by EdanPyx** [comment]
Ok well I only signed up to fix the lambda issue.

**Comment by mathiasbynens** [comment]
Right, sorry :)

**Comment by mathiasbynens** [comment]
Thanks!

**Pull request closed without merging**
